sassoftware/vscode-sas-extension

package.json, server/src/sas/LanguageServiceProvider.ts, themes/sas-dark-color-theme.json, themes/sas-highcontrast-color-theme.json, themes/sas-light-color-theme.json
Setting custom sematic tokens to base from standard tokens laid out in the [semantic highlighting guide for vscode](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide).
An issue #13 was created to request support for syntax highlighting with the common themes instead of using the SAS Custom Themes.  Following the [semantic highlighting guide](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide), I was able to set a superType for all of the custom semantic token types.  This was an addition to the root package.json file.
The only way I was able to test was to delete the themes from the themes directory and start a debug session.  Then I copied the testFixture/SampleCode.sas file into a text file.  Then I was able to switch to multiple …
=> Standard Semantic Highlighting

client/src/session/rest/index.ts
It appears that altering value in the object got from vscode settings will result in error in this case, has to copy.
=> fix: copy vscode setting object (#43)

.vscode/settings.json
Since we already recommend prettier as the formatter of choice, and already source a config js for it, set it as the default formatter. #48
=> Make prettier the default formatter

.eslintignore, .eslintrc.js, client/src/components/profile.ts, client/tsconfig.json, server/src/sas/CodeZoneManager.ts, server/src/sas/SyntaxDataProvider.ts
What should our stance on enforcing dot notation be? I found some spots where javascript key notation is used for getting and setting values. I'd like to propose that we take a stance of using idiomatic typescript whenever possible, including using the dot syntax. 
It gets a bit trickier for any types. I'd propose that we leave the enforcement of the rule at error and manually suppress these on a case by case basis. I would think that for this issue, having a lot of manual suppressions would indicate some kind of design smell in the types that we'd want to address.
=> Enforce Dot Notation

.eslintrc.js
**Summary**
This adds a new rule to prevent unused imports in our code. Previously, this was a warning.
**Testing**
- Ran `yarn lint`
=> chore: add no-unused-vars rule to eslint

client/src/connection/rest/index.ts
The results window was being displayed for all code executions, regardless of whether or not an actual ODS result was created. This is because the code
is wrapped in ods html5; ... ods html5 close;
This generates an html file, even if it does not
have anything in it.
Signed-off-by: Joseph Henry <joseph.henry@sas.com>
**Summary**
I am now checking for a valid body in the HTML before it is displayed.
**Testing**
I ran simple tests like 
`proc options; run;`
and 
```
data _null_;
x=10;
run;
```
That do not produce any ODS output and confirmed that the Result window does not appear.
Other tests like 
`proc print data=sashelp.cars;run;`
does produce a Result.
=> fix: Only show Results window if result is generated #46.

client/src/commands/run.ts, client/src/connection/rest/index.ts, package.json, package.nls.json
Matching the defaults of SAS Studio and EG, and very similar to DMS.
Planning to submit additional commits to change the run behavior to be more consistent with SAS Studio, EG, and DMS by default. For example, Run Selected should run all the code if there is no selection. Also, the "Run" button on the toolbar should perform the "Run selected" command...  if there is a selection, run just the selection, if there is no selection run all the code.
=> Change Run and Run Selected behavior (including default keybindings) to be consistent with other SAS IDEs

client/src/components/AuthProvider.ts, client/src/components/profile.ts, client/src/connection/rest/auth.ts, client/src/connection/rest/identities.ts, client/src/connection/rest/index.ts, client/src/node/extension.ts
**Summary**
- Register SAS as an [AuthenticationProvider](https://code.visualstudio.com/api/references/vscode-api#AuthenticationProvider) to take standard VS Code authentication behavior, which means
- SAS account will sit in VS Code's standard Accounts menu
- Authentication can be shared in a standard way across different functionalities (run, content navi, etc.) and even different extensions in future
- Authentication can persist across VS Code sessions (#94)
- Support direct re-direct from SASLogon so that user don't need to copy/paste authorization code
- It also depends on server update
- It uses the standard https://vscode.dev/redirect as the single redirect uri
**Testing**
- Make sure no regressions. User can still paste authorization code
- Close and re-open VS Code, the …
=> feat: support authorization redirect

client/test/profile.test.ts
**Summary**
Removes "only" function that was errantly causing only the profile test suite to run
**Testing**
1. rm -rf client/out
2. npm run test
3. Verify that all test suites including profile run as expected and pass.
=> fix: run all mocha tests

package.json
**Summary**
Quoting glob patterns on windows with single quotes generates errors when running 
`npm run lint`. 
Using double quotes and properly escaping the double quotes will resolve the issue.
**Testing**
1. Fixed lint script
2. Manually introduced a code lint issue
3. Run `npm run lint` from the terminal.  Verify that the error is properly reported in the terminal
4. Fix the manually introduced code lint issues
5. Run `npm run lint` again from the terminal. Verify that the script runs to completion with rc 0.
=> fix: double quote glob patterns when linting

client/src/components/LibraryNavigator/LibraryModel.ts, client/src/components/profile.ts, client/src/node/extension.ts, package.json
**Summary**
This is a change set made to be an addition onto adding Library support https://github.com/sassoftware/vscode-sas-extension/pull/143
If a direct connection is being made (IE, using the compute REST API but not going through Viya services, authentication is not done viya SASLogon, so the authentication requirement is not valid.
This change allows the Libraries view when a direct connection is established but also disables the content browser, since the Files and Folders service is not available.
**Testing**
I made sure that libraries show up with a direct connection.
=> fix: Support SAS Library viewer with a direct connection.

client/src/components/ExtensionContext.ts, client/src/connection/rest/index.ts, client/src/node/extension.ts, package.json
Commands are usually for end users or cross-extensions communication. Seems not necessary for internal calls.
This PR is just illustrating the idea to wrap the extension context. What should be exposed can be discussed.
For example instead of exposing a general `set/getContextValue`. We can expose just `set/getSessionId` and maintain the context key (SAS.sessionId) internally. So each invocation won't need to find the context key.
=> setContext without command

client/src/components/ContentNavigator/ContentModel.ts, client/src/components/ContentNavigator/const.ts, client/src/components/ContentNavigator/index.ts
**Summary**
Fix #156 
I noticed that the folder service does not check the special characters so I changed the folder name validator to only check the max length. If the name is more than 100 characters, there would be a new error message.
And change the validator for the new file name to allow Chinese characters (as well as other languages)
**Testing**
Test case in #156
=> fix: improve the new file/folder name validator (#156)

client/src/components/profile.ts, client/src/connection/index.ts, client/src/node/extension.ts, client/test/components/profile/profile.test.ts, client/test/extension.test.ts
**Summary**
- Removes code that was errantly not migrating all legacy profiles over. This was due to use of foreach inside of a promise, which will not run to completion.
- Additionally add a validator to profile validator to detect a missing connectionType property when `getSession()` is called during execution.
**Testing**
=> fix: remove foreach when iterating with promise

client/src/components/ContentNavigator/ContentModel.ts, client/test/components/ContentNavigator/ContentDataProvider.test.ts
**Summary**
fix the issue #191 
validate the new name with folder service before requesting the rename action
**Testing**
As described in #191 
Add unit tests
=> validate the new name before rename

CHANGELOG.md, README.md, client/src/components/profile.ts, client/src/connection/ssh/index.ts, client/test/components/profile/profile.test.ts, client/test/connection/ssh/index.test.ts, package.json, package.nls.json
**Summary**
- Adds support for encrypted private keys that are registered with ssh-agent
- Private Key file is removed from the connection profile and new connection prompts and is now instead defined in the global ssh config
- SSH Connection Provider is updated to read process.env.SSH_AUTH_SOCK (env var) and set Client agent property to this value at connection time
1. Enabled open ssh client optional feature
2. Created env variable SSH_AUTH_SOCK with value //./pipe/openssh-ssh-agent (windows uses a named pipe for the auth sock)
3. Ensure ssh-agent service is running, set startup type to automatic
4. Define an entry in $HOME/.ssh/config of the form:
```  
Host host.machine.name 
AddKeysToAgent yes
IdentityFile /path/to/private/key/with/passphrase 
``` 
5. Add the private key to …
=> feat: ssh agent auth

README.md, client/src/components/AuthProvider.ts, client/src/components/ContentNavigator/index.ts, client/src/components/LibraryNavigator/index.ts, client/src/components/profile.ts, client/src/node/extension.ts, package.json
**Summary**
This fixes some inconsistencies and bugs around the 0.1.3 deployment. Here's the summary:
- Fixes an issue in a readme
- Fixes a missing refresh command for SAS content
- Adds the ability to collapse libraries
- Fixes a console error when there is no active profile
- Fixes a bug where _no_ profile resulted in endlessly writing to user settings
- Fixes a bug where _no_ profile didn't allow users to sign in using the SAS sign in view
**Testing**
=> fix: fix miscellaneous bugs for 0.1.3 deployment

client/src/components/ContentNavigator/ContentModel.ts
**Summary**
fix #210 
The folder services returns 409 error if the folder contains non folder item even if add recursive parameter. So have to delete the children manually before delete the outer folder.
**Testing**
As described in #210
=> able to delete recursively

README.md, client/src/components/AuthProvider.ts, client/src/components/ContentNavigator/index.ts, client/src/components/LibraryNavigator/index.ts, client/src/node/extension.ts
**Summary**
This addresses a couple things:
- It un-authorizes a user (thus, hiding sas content / libraries) when switching a profile
- If adds a namespace for session storage. Right now, this is using "profile name" to store the information
- It updates `SECRET_KEY` to blow out the original cache
- It refreshes libraries when a profile is changed, and makes sure our event subscriber for changing a profile is cleaned up by vscode
**Testing**
- Tested setting up and switching between multiple profiles
- Made sure sas content and libraries were updated when logging back in (NOTE: Right now, you can see stale libraries when switching profiles. Once a new compute session is generated, they should be refreshed. That's expected behavior for this pass)
=> fix: address various auth issues

CHANGELOG.md, client/src/components/profile.ts, client/src/connection/rest/auth.ts, client/test/components/profile/profile.test.ts
**Summary**
This fixes an issue where trailing slashes can lead to 404/connection errors. This solves the issue in two ways:
- It trims slashes when creating new profiles
- It upgrades legacy profiles to add a trailing slash
**Testing**
=> fix: fix trailing slash on viya profile endpoints

.github/workflows/pr.yml
**Summary**
vsce has been deprecated and renamed to @vscode/vsce See https://www.npmjs.com/package/vsce
**Testing**
See build pass and no deprecation message anymore.
=> chore: update vsce

client/src/components/ContentNavigator/ContentModel.ts, client/test/components/ContentNavigator/ContentDataProvider.test.ts
**Summary**
This gets rid of order by contentType === 'folder', as that was causing 400 issues w/ sas content
**Testing**
- Made sure there were no 400 errors
- Made sure ordering looked correct
=> fix: fix content ordering

client/src/components/ExtensionContext.ts, client/src/connection/rest/index.ts, client/src/connection/rest/job.ts, client/src/connection/rest/server.ts, client/src/node/extension.ts, package.json
A sas session connection is made as needed by the extension. This session is maintained throughout the vscode session. Many things can cause the extension to reload (browser refresh, vscode reload, etc) and this causes a new connection to be established, which creates a brand new SAS session.
If an existing session is available, we should reconnect to it.
This is gated behind a REST profile option "reconnect"
**Summary**
Added a way to store key value pairs that persist through extension reloads. This uses the extension context.
If a sessionId is found, that session will be attempted to be reconnected to. If this succeeds, all future interaction will be
done on that session instead of creating a new on.
This also fixes a bug in JobState which causes unwanted server spam.
**Testing**
I …
=> feat: Reconnect to existing SAS Session if possible.

CHANGELOG.md, client/src/components/CAHelper.ts, client/src/node/extension.ts, package.json, package.nls.json
**Summary**
Fix #220
Add a configuration field so that user can provide their certificates
This page describes some background. But the VS Code extension provided by this page does NOT really work.
https://github.com/ukoloff/win-ca
I'll update the FAQ page once this merged.
**Testing**
1. Export a crt file from browser against an endpoint with self-signed certificate.
2. In VS Code settings UI, click "Add Item" under "User Provided Certificate" entry, enter the full file path for the crt file.
3. Restart VS Code and Sign in, success
=> feat: support user provided CA certificates

client/src/components/profile.ts, client/src/node/extension.ts, package.json
This was added in the original change for #143, but somehow it got overwritten.
This simply adds back the enabling of the library viewer when we have a direct connection.
**Summary**
Enable the library view when a direct connect is enabled. This does not require authorization to a Viya server, but it is using a REST connection
**Testing**
I made sure that the libraries are available when connecting in a direct fasion.
=> fix: Add back library support for direct SAS connections.

client/src/components/ContentNavigator/ContentModel.ts, client/test/components/ContentNavigator/ContentDataProvider.test.ts
**Summary**
Fix #264 
A file/folder resource could be shown up in different tree path (like /My Folder/folder1 and /SAS Content/Users/.../My Folder/folder1). The Tree view requires that each node must have unique id but currently the same resource in the different path has same id so the error occurs
**Testing**
As described in #264
=> Make each tree item has unique id

client/src/components/LibraryNavigator/LibraryModel.ts
**Summary**
Fix #309
The issue is part of regression introduced by #301
It turns out to be tricky to set the accept header for getting library summary we want on various Viya versions. Neither more specific mime type "application/vnd.sas.compute.library.summary+json" nor more broader default type works. "application/json" appears the only one that can get expected result on all endpoints I tested.
However "application/json" doesn't work for other requets. They still need "application/vnd.sas.collection+json"
**Testing**
Tested library view on both Viya3.5 and Viya4
=> fix: library summary accept header

client/src/components/ContentNavigator/index.ts
**Summary**
Fix #317
Currently Content Navigator will connect new endpoint whenever profile changed. It should limit to the profiles that support content.
**Testing**
Test case in #317
=> fix: do not connect content when not supported

client/src/commands/run.ts, client/src/connection/rest/index.ts
**Summary**
Support #187
Currently only for Rest. (I guess SSH can't really cancel like Rest. It can only close session.)
**Testing**
Click the `Cancel` button on the `SAS code running...` progress notification.
=> feat: support cancelling running job

client/src/components/profile.ts, client/src/connection/com/index.ts, client/src/connection/rest/index.ts, client/src/connection/rest/server.ts, client/src/connection/ssh/index.ts
**Summary**
Promotes sasOptions to a new BaseProfile interface so that all Connection Providers have access to it. Rest Connection Provider inspects new sasOptions profile to set them on the compute session api request if present.
**Testing**
1. Create a new rest connection profile with the following sasOptions: ```["-PAGESIZE=MAX"]```
Example:
```
"rest-conn": {
"connectionType": "rest",
"endpoint": "[...]",
"reconnect": "true",
"sasOptions": [
"-PAGESIZE MAX"
]
},
```
2. Run the following test code:
```proc print data=sashelp.cars; run;```
Should get 428 observations. Should see the Result tab with ODS results.
3. Run the following test code:
```proc options option=PAGESIZE value; run;```
Should get the following log output:
```
1    ods html5;
NOTE: Writing HTML5 Body file: sashtml.htm …
```
=> feat: SAS Options support for rest connection profiles

CHANGELOG.md, client/src/components/ExtensionContext.ts, client/src/connection/rest/identities.ts, tools/check-copyright.mjs
**Summary**
This updates our copyright check script to run on all _valid_ files, instead of those added in a recent commit. You can run this check manually via `npm run copyright:check`. This is also ran via github actions.
Additionally, this adds a fix flag (`npm run copyright:check --fix`) that will automatically prepend copyright information to files that are missing it.
**Testing**
=> fix: fix copyright check script

client/src/commands/closeSession.ts, client/src/commands/run.ts, client/src/components/ContentNavigator/index.ts, client/src/components/notebook/Controller.ts, client/src/components/profile.ts, client/src/connection/com/index.ts, client/src/connection/index.ts, client/src/connection/rest/index.ts, client/src/connection/rest/server.ts, client/src/connection/rest/session.ts, client/src/connection/session.ts, client/src/connection/ssh/index.ts, client/test/connection/com/index.test.ts, client/test/connection/ssh/index.test.ts, package.json, package.nls.json
**Summary**
Adds autoexec support to the rest connection profle. AutoExec can be setup in multiple ways, by referencing one or more external files that are readable by vscode:
``` json
"rest-profile-1": {
"connectionType": "rest",
"endpoint": <...omitted...>,
"autoExec": [{
"type": "file", 
"filePath":"/file/path/one.sas"
},{
"type":"file",
"filePath": "/file/path/two.sas"}
]
}
```
By directly embedding SAS lines into the connection profile:
``` json
"rest-profile": {
"connectionType": "rest",
"endpoint": <...omitted...>,
"autoExec": [{
"type": "line", 
"line":"libname _all_ list;"
},{
"type":"line",
"line": "%put _all_;"}
]
}
```
Or by using a mix of the two approaches:
``` json
"rest-profile": {
"connectionType": "rest",
"endpoint": <...omitted...>,
"autoExec": [{
"type": "line", …
```
=> feat: autoexec support for viya connection

client/src/components/utils.ts, client/src/connection/rest/job.ts
**Summary**
Fix #330
There can be many ODS graphs in the result list. We should retrieve all pages of results.
**Testing**
Test case in #330
=> fix: get all pages of results

client/src/components/profile.ts
**Summary**
Fix #389
The `vscode.window.showInputBox` API will return `undefined` when user press ESC to cancel. We should really cancel the process when user choose to cancel.
**Testing**
Test case in #389
=> fix: ability to cancel profile update

client/src/connection/rest/index.ts
**Summary**
Checks that onLogFn has been set before printing out the session log for viya connections to prevent null reference errors.
**Testing**
Repro steps from the issue.
=> fix: check that _onLogFn exists before calling in printSessionLog

client/src/commands/run.ts, client/src/components/LibraryNavigator/LibraryModel.ts, client/src/components/LogChannel.ts, client/src/connection/rest/index.ts, client/src/connection/rest/session.ts, client/src/connection/session.ts
**Summary**
Check the session job status before streaming the log to avoid various timing problems. Additionally, LibraryModel is currently creating a session. Modify LibraryModel to attach the log handler when LibraryModel creates a session in order to see the session log when LibraryModel invokes session setup. Fixes current issues where if the user opens the Library Panel first, before executing code, then the session log will not be output to the channel. Additionally, when running the actual sas file, it would also not be seen there, which is not desired behavior.
**Testing**
Test case in #369
=> refactor: Session Log Streaming

client/src/connection/com/index.ts, client/src/connection/com/script.ts
=>  fix: regex to match html5 file name in local COM

client/src/components/LibraryNavigator/LibraryModel.ts
**Summary**
Viya 3.5 appears to not allow start parameter greater than count.
**Testing**
See table showing correctly on Viya 3.5 and Viya 4
=> fix: start should not exceed count in request parameter

client/src/components/ContentNavigator/ContentModel.ts, client/test/components/ContentNavigator/ContentDataProvider.test.ts
**Summary**
Fix #328 
There is something wrong with the folder service (version 2.74.2) on Viya 2023.03 LTS. The members query fails because of sortBy parameter 'eq(contentType, 'folder')'. (It works on 2022.09 and 2023.04).
To avoid this failure, remove this sortBy parameter. The side effect is that the folders may not be ordered first.
**Testing**
Test as the reproduce steps.
=> fix: able to show content on 2023.03 (#328)

client/src/commands/run.ts, client/src/node/extension.ts, package.json
**Summary**
Fix #433
When a command is invoked from a menu, VS Code will pass the URI of the triggered resource as the first parameter.
We should utilize it over `vscode.window.activeTextEditor` (which is the editor with focus, thus could be SAS log).
**Testing**
- Be able to directly click the running man icon when focus is not in the SAS code. The code submitted is correct.
- Not be able to run when it's already running (running man icon disabled)
=> fix: always show running man icon

client/src/connection/ssh/index.ts, client/test/connection/ssh/index.test.ts
**Summary**
Fix #458
This is a regression introduced by
https://github.com/sassoftware/vscode-sas-extension/pull/355/files#diff-93c2ba90afbd1237f6041f9b12f380c455911f4275dc33ea8ebde51ce1031f75L197
It should only resolve for setup, not for running.
Prevously it relied on if _onLogFn was passed in. Now we can rely on the setup timer existence.
**Testing**
Test case in #458
=> fix: ssh setup resolve

client/src/connection/rest/index.ts
**Summary**
Relaxes the check on compute job state to check for results even if the job errors out. This has the added benefit of showing results that are valid, in scenarios where part of the code produced results, but a subsequent part of code resulted in a compute job error state.
**Testing**
Test case in #467
=> fix: check job results for success or error

.vscode/launch.json, client/test/index.ts
**Summary**
Currently it always run all tests. As a developer, I'd like to only debug my test.
**Testing**
1. Open my test file in VS Code, say `client/test/connection/ssh/index.test.ts`
2. In the `Run and Debug` panel, select `Language Server E2E Test` and start debugging.
3. Notice that only the tests in current file is run.
Also verified that `npm run test` still run all tests
=> chore: ability to debug single test file

tools/build.mjs, webpack.config.js
**Summary**
From #482
Move notebook renderer build from webpack to esbuild, so that the `watch` script can build everything needed for Launch Client.
Added `format: "esm"` which is required for the notebook renderer to be invoked by VS Code engine. It looks also makes sense to DataViewer as it is currently imported as a [module](https://github.com/sassoftware/vscode-sas-extension/blob/main/client/src/panels/DataViewer.ts#L54).
**Testing**
1. Clean up `client/dist` directory.
2. Click `Launch Client` in VS Code.
3. Verify that notebook result and data viewer works well.
=> build: move notebook renderer build to esbuild

client/src/connection/com/index.ts, client/test/connection/com/index.test.ts
Signed-off-by: Shuguang Sun <shuguang79@qq.com>
**Summary**
See https://github.com/sassoftware/vscode-sas-extension/issues/356 . 
**Testing**
Not provide test code. But tested below scenarios:
- `$` symbol
- `%put "ab'c";`
=> fix(core): escape $ symbol in powershell code for local connection

client/src/connection/ssh/index.ts
**Summary**
Fix #483
The data callback will be called multiple times, each time with a piece of the file content. The splitting can happen at any places.
For example, `<td class="r">12</td>` can be split into `<td ` (with trailing whitespace) and the rest part. If trimmed, it will become `<tdclass="r">12</td>` after combination which is not a valid HTML.
It is critical and a data integrity issue.
**Testing**
Test case in #483
=> fix: should not trim HTML buffer

.github/workflows/pr.yml, .github/workflows/translations.yml
**Summary**
This makes a few change to how we check for translations:
- It splits this into a distinct workflow that is ran on a push to `main` (instead of checking for every pull request action)
- It also adds a `workflow_dispatch` trigger such that we can manually run this check with any branch
- It updates the output to only list the files that need to be updated for translations. See the two examples below
Example with no translations needed:
Example with translations needed: 
**Testing**
=> feat: improve translation check

client/src/commands/run.ts, client/src/components/utils.ts, package.json, package.nls.de.json, package.nls.json, package.nls.zh-cn.json
**Summary**
Enabling HTML output has nothing to do with "session"; so, changed the ID to results.html.enabled which makes more sense, follows pattern with results.html.style, and easier to extend to other results formats in the future. Also, I think it makes more sense for the connection profiles (and related certificates) to appear first, since that is usually the first thing you do when getting going with the extension.
**Testing**
- Ensured the extension settings are now in the desired order. (Note: When you open the extension settings from the extension in the Extensions pane, it looks like the settings are in alphabetical order rather than the specified order. To see the specified order, type "sas" in the search field or select Extensions->SAS in the settings tab.)
- Ensure the …
=> feat: change output html option to more logical/consistent ID and re-order options

client/src/components/ContentNavigator/ContentModel.ts
**Summary**
Fix #507. Add Content-Type: "application/vnd.sas.file+json" in the header when renaming an item
**Testing**
As described in #507.
=> fix: add proper content-type for rename (#507)

client/src/components/ContentNavigator/index.ts
**Summary**
fix #504 
Do not rename when cancelling the input box
**Testing**
as described in #504.
=> fix: do not rename when cancel input (#504)

client/src/webview/DataViewer.css, client/src/webview/DataViewer.tsx
**Summary**
Prior to this change, we checked to see if we were using a dark theme and applied the `ag-alpine-theme-dark` theme. This changes makes it such that we target `ag-alpine-theme-dark` for both dark and high contrast dark themes, and default to the light theme `ag-alpine-theme` in other cases
**Testing**
=> fix: update high contrast data viewer theming

client/src/commands/run.ts, client/src/components/Helper/SasCodeHelper.ts, client/test/components/Helper/SasCodeHelper.test.ts
implements #521 
**Summary**
Add code to set environment variable SAS_EXECFILEPATH to the full path and filename of the SAS program code is being submitted from
**Testing**
manually tested against local SAS 9.4 profile
=> Assign _SASPROGRAMFILE macro-variable to full path and filename of submitted SAS program (Local SAS 9.4)

client/src/commands/run.ts, client/src/components/Helper/SettingHelper.ts, client/src/components/ResultPanel.ts, client/src/components/tasks/SasTasks.ts, package.json, package.nls.json
**Summary**
Resolve #62
Added `Display results to the side of the code` setting. If uncheck, it will display Result in the same tab group to the submitted code.
Added `Reuse single panel to display results` setting. If uncheck, it will display new Result panel each time.
**Testing**
By default the behavior is same to current version. Tested combinations of different settings.
=> feat: option to control the default placement of Result panel

client/src/components/ContentNavigator/ContentModel.ts
**Summary**
Fix #533
The content-type is invalid when the renaming item is a folder or favorite.
**Testing**
As described in #533
=> fix: rename folder failed (#533)

client/src/components/ContentNavigator/convert.ts, client/src/components/ContentNavigator/index.ts, client/src/components/ContentNavigator/utils.ts, client/test/components/ContentNavigator/convert.test.ts, package.json
**Summary**
Removes conversion of .ipynb to flow. We only want to support converting .sasnb files to flow.
Removes default association of .ipynb to the sas-notebook component since this causes .ipynb files to no longer render when opened.
**Testing**
Steps in #537
=> fix: associate sas-notebook with sasnb only

CHANGELOG.md, client/src/components/ContentNavigator/ContentDataProvider.ts, client/src/components/ContentNavigator/ContentModel.ts, client/src/components/ContentNavigator/const.ts, client/src/components/ContentNavigator/index.ts, client/src/components/ContentNavigator/utils.ts, client/test/components/ContentNavigator/ContentDataProvider.test.ts, package.json
**Summary**
This does a few things to improve the sasnb -> dataflow experience:
- Provides visual indication of converting a notebook to dataflow
- allows converting sasnb files to notebooks from the explorer view (We default to storing notebooks in "My Folder")
- updates messaging to indicate _where_ a notebook was created (mainly to clear up confusion about where the dataflow went)
- updates sas content to display created dataflow files, and updates content model to display `FileOpenError` when trying to open files
**Testing**
=> feat: allow convert to flow for explorer files

client/src/commands/run.ts, client/src/connection/index.ts, client/src/connection/rest/session.ts
**Summary**
Check for failed state when streaming the session log to avoid attempting to check for logs in an unbounded loop.
**Testing**
Steps in #562
=> fix: check for failed state during session log stream to prevent unbounded loop

.github/dependabot.yml
**Summary**
Looks like our current dependabot doesn't cover `/client` and `/server`. Guess it's a good idea to also keep them updated.
**Testing**
N/A
=> chore: dependabot for /client /server and github-actions

client/src/components/StatusBarItem.ts, client/src/connection/com/index.ts, client/src/connection/rest/index.ts, client/src/connection/ssh/index.ts, client/src/node/extension.ts, connect-and-run.md, package.json
**Summary**
Resolve #119
- Remove the disconnect button from the editor toolbar (next to the run button), as it's not specific to a file.
- Change the icon of the active profile status bar item when a compute session established to provide visual indication.
- Add `Close Session` button on the tooltip of the active profile status bar item when a compute session established.
- Add `SAS Profile` title to the tooltip of the active profile status bar item
- (Engineering) Extract status bar related code to a separate file
**Testing**
Create and close sessions to see the changes.
=> feat: close session on status bar

client/src/components/utils/sasCode.ts
**Summary**
Adds ods graphics on; to ods wrapper code to better align with SAS Studio
**Testing**
1. Run a program  (example below).
```
title 'Shoe Sales Over $500,000';
data work.shoes;
set sashelp.shoes;
where sales>500000;
run;
```
2. Check the Output Log. Verify that ods graphics on; appears in the output log as a line.
=> feat: ods graphics on; in wrapper

server/src/sas/LanguageServiceProvider.ts
**Summary**
Fix #715
VS Code now appears to require non-empty name for document symbol. Added guard check.
**Testing**
Test case in #715
=> fix: document symbol requires non-empty name

package.json
**Summary**
Resolve #735 
**Testing**
Copy codes with datalines/cards, no redundant whitespace will be inserted in front of each line, and codes will run normally.
=> fix: add formatonpaste configuration

CHANGELOG.md, README.md, client/package-lock.json, client/package.json, package-lock.json, package.json
**Summary**
Fix #764
One of our auto-updated dependency required VS Code 1.82
https://github.com/sassoftware/vscode-sas-extension/pull/644/files#diff-925cb809ce77c7f7f7f8bbd7594593438fc006dc56bf432a624c47722a784d3dR621
**Testing**
N/A
=> doc: update VS Code requirement to 1.82

client/src/connection/itc/index.ts, l10n/bundle.l10n.zh-cn.json
Fix https://github.com/sassoftware/vscode-sas-extension/issues/734
Suggestion from [jbodart-argenx](https://github.com/jbodart-argenx): https://github.com/sassoftware/vscode-sas-extension/issues/685#issuecomment-1849425397
1. Externalized error message 'There was an error executing the SAS Program. See [console log] for more details.'
2. The 'console log' in the show error message dialog should be a link to open the developer tools.
Testing
1. Change the language to zh-cn to check if the error message is change to Chinese.
2. Click the hyper link [console log] to see if the developer tools is opened.
=> fix: externalized error message and toggle developer tools (#734)

.github/workflows/translations.yml
**Summary**
@vscode/l10n-dev is not compatible with current lts node. This PR pins the version to a known version that works.
**Testing**
Run action locally. L10n files needing localization are now properly identified. Those keys will get updated using our normal L10 process.
=> fix: pin node version to avoid compatibility issues

client/src/commands/run.ts, client/src/components/LibraryNavigator/LibraryAdapterFactory.ts, client/src/components/LibraryNavigator/LibraryDataProvider.ts, client/src/components/LibraryNavigator/LibraryModel.ts, client/src/components/LibraryNavigator/PaginatedResultSet.ts, client/src/components/LibraryNavigator/index.ts, client/src/components/LibraryNavigator/types.ts, client/src/components/notebook/Controller.ts, client/src/connection/itc/index.ts, client/src/connection/rest/RestLibraryAdapter.ts, client/src/connection/rest/index.ts, client/src/connection/session.ts, client/src/connection/ssh/index.ts, client/test/components/LibraryNavigator/LibraryDataProvider.test.ts, client/test/components/LibraryNavigator/PaginatedResultSet.test.ts
**Summary**
This refactors LibraryDataProvider in preparation for getting things working with iom/com connections. Here's the general architecture changes made as part of this pr:
- The concept of a `LibraryAdapter` has been introduced along with `RestLibraryAdapter`. `LibraryAdapter` is an interface that is used by LibraryModel to manage library/table data
- `LibraryAdapterFactory` has been added to create `LibraryAdapter`s. At the moment, this always creates a `RestLibraryAdapter`, but will eventually create a `ItcLibraryAdapter`
- `LibraryModel`s functionality has been limited to: working with the file system, paginating api requests, and further processing library adapter results for easier consumption by `LibraryDataProvider`
**Testing**
=> chore: create library adapter, make library model api agnostic

CHANGELOG.md, client/src/components/LibraryNavigator/LibraryModel.ts, client/src/components/LibraryNavigator/index.ts, client/test/components/LibraryNavigator/LibraryDataProvider.test.ts, package.json
**Summary**
This updates our library model such that it accepts an undefined library adapter. This fixes a login issue where users don't have profiles available.
**Testing**
- Removed all profiles and added a new one
- Made sure libraries loaded upon login
=> fix: add activeProfile check when creating library model

README.md
**Summary**
The link for SAS Programming documentation has changed, the old one is "Page not found" now.
**Testing**
Click the link for SAS Programming documentation and see correct page.
=> doc: update link for SAS Programming documentation

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
**Summary**
This removes Casey & Tom as the default assignees for new bugs/issues
**Testing**
👀
=> chore: remove default assignees from issue templates

CHANGELOG.md, package.json
**Summary**
This removes `SAS: Sign in` from the command palette in an attempt to prevent errors related to trying to use this with non-viya profiles.
**Testing**
=> fix: remove sign in from command palette

client/src/connection/itc/LineParser.ts, client/src/connection/itc/const.ts, client/src/connection/itc/index.ts, client/src/connection/itc/script.ts, client/src/connection/itc/util.ts, client/test/connection/itc/index.test.ts
**Summary**
This adds better error support for IOM & COM connections. Specifically, it provides _better_ errors for:
- being on the wrong plaform (i.e. Mac)
- using an incorrect username / password
- using an incorrect host
- using an incorrect port (or having a connection where a sas server isn't present)
- trying to run code that will trigger transcoding errors
**Testing**
=> feat: add better error reporting for COM/IOM connections

client/src/components/logViewer/index.ts
**Summary**
Fix #886
In most cases, a log line returned from server doesn't contain line separator. It fits the `outputChannel.appendLine` API well.
It appears that in the case of #886, a log line returned from server contains a trailing line separator, which produces an unexpected extra line and messed the log type index.
 
**Testing**
Test case in #886
=> fix: trim trailing line separator for SAS log

server/src/sas/CompletionProvider.ts, server/src/sas/SyntaxDataProvider.ts
**Summary**
Fix #905
`getProcedureStatementOptionValues` has to call callback even no data returned, so that function autocomplete can appear.
**Testing**
Test case in #905
=> fix: display function autocomplete at some special cases

client/src/components/utils/sasCode.ts, client/src/connection/itc/index.ts, client/test/connection/itc/index.test.ts
**Summary**
Add `ods html5;` to function `wrapCodeWithOutputHtml` and make it similar to SAS EG.
The reason to make the change is that the SAS will generate html files in th 'current' diretory instead of 'work' directory. For exampl, I can change the current directory with `%put %sysfunc(dlgcdir("&__prjpath./SAS"));`, and then SAS will generate the html file in the path of '&__prjpath./SAS', however, vscode-sas-extension wants find the file in the work directory.
There is a function in 'client/src/connection/com/index.ts' which try to correct the ods output path and depends on `ods html5;`
```ts
//write ODS output to work so that the session cleans up after itself
const codeWithODSPath = code.replace(
"ods html5;",
`ods html5 path="${this._workDirectory}";`,
);
```
**Testing**
Using the …
=> fix(core): ods html5 output path to work directory

client/src/connection/itc/index.ts, client/src/connection/itc/util.ts, client/test/connection/itc/util.test.ts
**Summary**
This fixes an issue where passwords weren't having special characters replaced as expected
**Testing**
=> fix: fix password parsing

client/src/connection/itc/ItcLibraryAdapter.ts
**Summary**
Now in the library for the ITC session, json is print to log in a long line which might exceed the limit of SAS if the data set is too large. Now we add the `pretty` option to `proc json` which makes each line of the json file short and it help SAS print full json file to log.
**Testing**
Prepare a large dataset, and open it in library.
=> chore: using pretty for json output to avoid long line

client/src/connection/itc/script.ts
**Summary**
Fix #868
Pass an empty string to the `AssignFileref` call and it will create a temporary fileref that will never conflict with user code.
**Testing**
Test case in #868
=> fix: Fileref OUTFILE should be allowed for COM/IOM

client/src/connection/itc/index.ts, client/src/connection/itc/script.ts, client/test/connection/itc/index.test.ts
**Summary**
Fix #964
When the default working directory name is long, it may wrap into multiple lines in SAS log. The `WORK_DIR_END_TAG` may be break into 2 lines thus not captured.
We're injecting log type between each log line, so when parsing across multiple log lines, it has to process LogLineType first, otherwise the log line type will be captured as part of working directory name, which is wrong.
**Testing**
Make default working directory be a pretty long name and try run code.
=> fix: IOM connection hang when work dir is long

.github/workflows/translations.yml
Reverts sassoftware/vscode-sas-extension#786
Looks like the issue was resolved now
=> Revert "fix: pin node version to avoid compatibility issues"

client/src/connection/ssh/index.ts
**Summary**
Fix #1005
`env` command seems work across sh and csh.
**Testing**
Tested it with sh and csh
=> fix: support cshell for ssh

client/src/components/logViewer/sasDiagnostics.ts
**Summary**
The problem related with a sas file should be clear if there is no problem in its log.
**Testing**
see issue #1017 description.
=> fix: problems are not clear when there is no problem in log (#1017)

client/src/components/ContentNavigator/ContentModel.ts, client/src/components/ContentNavigator/const.ts, client/src/components/ContentNavigator/utils.ts
**Summary**
Previously, saving files would always convert the content type to text/plain. This changes things such that we maintain the content type on save.
Additionally, this makes a few small refactoring changes:
- This moves a couple of helper functions from ContentModel to utils
- It removes some unnecessary writes to file metadata
**Testing**
=> fix: fix content type when saving files

language-configuration.json, server/src/sas/CodeZoneManager.ts, server/src/sas/FormatOnTypeProvider.ts
Summary
Resolve https://github.com/sassoftware/vscode-sas-extension/issues/522
Testing
1 Enter "run" after "=", indentation will not be reduced.
2 Enter "run" instead of after "=", indentation will decrease normally.
=> fix: prevent decrease indentation when the word run is used as value

client/src/webview/useDataViewer.ts
**Summary**
Fix #1096
Refers to https://www.ag-grid.com/react-data-grid/upgrading-to-ag-grid-32
Also added type annotation `GridReadyEvent` so that this kind of error can be captured by TS build.
**Testing**
Test case in #1096
=> fix: resolve the breaking change introduced by AG Grid 32.0

client/src/connection/itc/ItcLibraryAdapter.ts, client/src/connection/itc/script.ts
**Summary**
Fix #1012
Put the start tag in the same statement with macro resolution so that it will be after the extra log produced by `options symbolgen` 
**Testing**
Test case in #1012
=> fix: library pane crash with option symbolgen

client/src/connection/itc/CodeRunner.ts, client/src/connection/itc/ItcLibraryAdapter.ts, client/test/connection/itc/Coderunner.test.ts
**Summary**
Fix #1022
During code executing, if 2 or more `runCode` calls happen, they're waiting for a same thing and will execute at same time.
The fix is to queue the `runCode` call, and also refactored the `CodeRunner` class to be a static module, as the execution has to be limited to 1 globally.
Note that the original `runCode` implementation was NOT changed at all except renamed to `_runCode`. It may not be obvious in the diff as the indentation was changed.
**Testing**
Test case in #1022
=> fix: queue run code

client/src/webview/DataViewer.tsx, client/src/webview/columnHeaderTemplate.ts, client/src/webview/useDataViewer.ts
**Summary**
Fix #1114, #1013
AG Grid changed its template via https://github.com/ag-grid/ag-grid/pull/7998
I don't see any announcement for this breaking change. This is really bad.
Disabled sort UI as there's no such functionality right now.
**Testing**
Test case in #1114 and #1013
=> fix: match latest ag grid template

client/src/components/utils/SASCodeDocument.ts, client/src/connection/rest/job.ts, client/test/components/util/SASCodeDocument.test.ts
**Summary**
Simple workaround to introduce a newline at the end of the postamble to ensure that the last bit of log displays properly in the given error scenario. We'll be following up internally with the compute api team to understand why this is required.
**Testing**
Sample program from #963 for 9x and Viya connections.
=> fix: workaround compute log display issues

client/src/connection/ssh/index.ts
**Summary**
Fix #1070
In SSH connection, if a data stream line ends with `?`, it's a SAS prompt line and not part of SAS log. It appears that in some rare cases, there'll be trailing white spaces after `?`. I don't know why but let's simply trim it.
**Testing**
Test case in #1070
=> fix: trim prompt line in ssh

syntaxes/sas.tmLanguage.json, syntaxes/sassql.tmLanguage.json
**Summary**
Fix #1213
VS Code will NOT match brackets in strings. Macro quote doesn't need to be treated as string.
**Testing**
Test case in #1213
=> fix: allow bracket matching in macro quote

client/src/components/logViewer/index.ts, client/src/connection/itc/CodeRunner.ts, client/src/store/run/actions.ts, client/src/store/run/initialState.ts, client/test/store/run/actions.test.ts
**Summary**
Fix #1243
ITCLibraryAdapter internally runs SAS code. We should not clear log in this case.
**Testing**
Test case in #1243
=> fix: should not clear log for non-user running

client/src/components/ResultPanel/ResultPanel.ts
**Summary**
Resolve #700
**Testing**
1. Run code to get HTML result
2. Focus in the Result pane
3. Press the find shortcut (by default Ctrl+F on Windows)
=> feat: enable find in result pane

client/src/connection/itc/LineParser.ts, client/src/connection/itc/index.ts
**Summary**
Fix #1266
The error happened after the parser had started capturing log lines. In the second time the parser is still in the stale state. We should reset the parser each time before getting the work dir.
**Testing**
Test case in #1266
=> fix: reset work dir parser each time

client/testFixture/formatter/expected.sas, server/src/sas/formatter/printer.ts
**Summary**
Fix #1288
When inside a region, it's not the first node but the second. The first node is the region start statement (e.g. `%macro;`)
**Testing**
Test case in #1288
=> fix: do not add empty line before the first section inside a region

client/src/components/ContentNavigator/ContentDataProvider.ts, client/test/components/ContentNavigator/ContentDataProvider.test.ts
**Summary**
Resolves #1299
We should not explicitly specify a general file icon so that VS Code can go with its default.
It honors user's [File Icon Themes](https://code.visualstudio.com/docs/getstarted/themes#_file-icon-themes)
**Testing**
See file icons in SAS Content and SAS Server same to VS Code Explorer view.
=> feat: inherit VS Code file icons in SAS Content and Server

CHANGELOG.md, server/src/python/browser/fakeFileSystem.ts, server/src/python/utils.ts, server/src/server.ts
**Summary**
Fix #1321
Root level indentation is not allowed
**Testing**
Test case in #1321
=> fix: language server exception for PROC PYTHON

server/src/sas/LanguageServiceProvider.ts
**Summary**
Resolves #1323
**Testing**
See macro name and the first dataset name in data step displayed in Outline pane.
=> feat: display macro name in outline

server/src/server.ts
**Summary**
Fix #1357
**Testing**
Test case in #1357
=> fix: remove unexpected endsubmit autocomplete

client/src/connection/rest/server.ts
**Summary**
Fix #1367
Remove the try block so that error will bubble up to the existing error handling.
**Testing**
Tested with Workbench and it can show error details same to Viya
=> fix: bubble server error up

client/src/components/notebook/Controller.ts, client/src/connection/itc/index.ts, client/src/connection/rest/index.ts, client/src/connection/session.ts, client/src/connection/ssh/index.ts, client/test/connection/itc/Coderunner.test.ts
**Summary**
Fix the problem described [here](https://github.com/sassoftware/vscode-sas-extension/issues/1212#issuecomment-2360386822)
Need to reject the current run promise when close session, otherwise it will never resolve or reject and user can't run again.
**Testing**
Close session in a long running, user can run again.
=> fix: reject run promise when close session

client/package-lock.json, client/package.json, client/src/components/notebook/exporters/index.ts, client/src/components/notebook/exporters/templates/dark.css, client/src/components/notebook/exporters/templates/default.html, client/src/components/notebook/exporters/templates/light.css, client/src/components/notebook/exporters/toHTML.ts, client/src/components/notebook/exporters/toSAS.ts, client/src/components/utils/settings.ts, client/src/node/extension.ts, package.json, package.nls.json, tools/build.mjs, website/docs/Features/sasNotebook.md
**Summary**
Provide the ability to export SAS Notebook to HTML file.
_Notes_
- Extensions do not have access to the VS Code DOM, we're not able to get what rendered in VS Code. Therefore the exported HTML may not look same to what you see in VS Code. Same thing happens for Jupyter extension.
- The exported HTML will be in Light or Dark theme depending on your current VS Code theme kind.
- By default it doesn't include SAS log into the exported HTML file. To include log, check the `SAS.notebook.export.includeLog` setting.
**Testing**
Open a `.sasnb` file, click `...` from the top toolbar and select `Export`, specify an HTML file name.
=> feat: export sasnb to HTML

client/src/commands/run.ts, server/src/server.ts
**Summary**
#991 changed the "sas/getFoldingBlock" LSP API, which broke other clients. The type (line/col) is not really the Position (line, character) type. Restore it.
**Testing**
Run Region works well as before
=> chore: restore getFoldingBlock LSP API

client/src/connection/rest/index.ts
**Summary**
Fix #1447
The `job.getLogStream()` call is already polling job state and resolve on job complete. Remove unnecessary get state calls.
**Testing**
See execution is a little faster.
=> fix: reduce unnecessary rest calls

client/src/components/APIProvider.ts, client/src/components/LibraryNavigator/LibraryDataProvider.ts, client/src/components/LibraryNavigator/LibraryModel.ts, client/src/node/extension.ts
**Summary**
Per https://github.com/sassoftware/vscode-sas-extension/pull/1437#issuecomment-2793090461
Provide `getLibraries` and `getColumns` API for REST connection.
`accessToken` is checked to make sure the caller is allowed. The caller extension needs to call `authentication.getSession` to get the access token which will prompt user to allow.
**Testing**
API can be called from other extensions
=> feat: provide getLibraries and getColumns API for Rest

client/src/components/logViewer/ProblemProcessor.ts
**Summary**
If there is first matching locations and problems, the initial beginning index should be 0, which is 1 before this fix.
fix #1475 
**Testing**
=> fix: correct default value for last found index in ProblemProcessor (#1475)

client/src/components/ContentNavigator/index.ts, client/src/connection/rest/util.ts
**Summary**
Fix https://github.com/sassoftware/vscode-sas-extension/issues/1272
**Testing**
the test#.sas can be open now;
the icon in the tree view is a correct sas icon;
it can create the xxx#.sas file from extension.
=> fix:deal with the hash sign

client/testFixture/formatter/expected.sas, client/testFixture/formatter/unformatted.sas, server/src/sas/formatter/parser.ts, website/docs/Features/sasCodeEditing.md, website/docusaurus.config.ts
**Summary**
Resolves #1197
User can now add a custom region as below, which will be ignored by SAS code formatter.
```sas
proc format library=library;
/* region format-ignore */
invalue evaluation 'O'=4
'S'=3
'E'=2
'C'=1
'N'=0;
/* endregion */
run;
```
Note that if your custom region intersect with other regions, the result may be unexpected.
**Testing**
See code within the custom region remain unchanged after performing "Format Document" command. Other code get formatted as expected.
=> feat: be able to ignore region from format

client/src/components/LibraryNavigator/index.ts
**Summary**
Set default CSV save location to workspace root as https://github.com/sassoftware/vscode-sas-extension/issues/952
**Testing**
How did you test this change?
Using ITC profile:
- local matchine + remote server: the save dialog starts from the the last used directory as before
- remote+SSH + remote server: the default diretory is the root of the workspace.
=> chore: Set default CSV save location to workspace root 

client/test/components/LibraryNavigator/LibraryDataProvider.test.ts, package-lock.json, package.json
**Summary**
Upgrading nock was leading to some strange errors around not being able to resolve the host. It looks like we were only using it for one test, where it makes enough sense to mock the compute api _instead_ of axios directly. 
**Testing**
=> chore: remove nock dependency
