- server/src/sas/LexerEx.ts
**Summary**
Fix #88 
**Testing**
The test code in #88
> recognize macro ending without semicolon

- server/src/sas/Lexer.ts
**Summary**
Fix #105 
**Testing**
Test case in #105
> fix: recognize nls character in dataset name

- .vscodeignore
- CHANGELOG.md
- README.md
- client/package-lock.json
- client/package.json
- client/src/commands/closeSession.ts
- client/src/commands/run.ts
- client/src/connection/index.ts
- client/src/connection/rest/auth.ts
- client/src/connection/rest/common.ts
- client/src/connection/rest/context.ts
- client/src/connection/rest/index.ts
- client/src/connection/rest/job.ts
- client/src/connection/rest/server.ts
- client/src/connection/rest/session.ts
- client/src/node/extension.ts
- package-lock.json
- package.json
- server/src/sas/Lexer.ts
- server/src/sas/LexerEx.ts
**Summary**
Prepare to publish a new version.
- Drafted changelog and readme changes
- Corrected a dependency. (`media-typer` is used in production code and should not be as devDependencies)
- Added vscodeignore entries for recent added files
**Testing**
No functional changes, no need to test
> prepare v0.1.2

- CHANGELOG.md
- README.md
**Summary**
This adds notes around SAS content changes
**Testing**
👀
> doc: update changelog/readme notes for SAS content

- client/src/components/AuthProvider.ts
- client/src/connection/rest/auth.ts
**Summary**
Fix #227
**Testing**
Don't ask for re-authentication on following running
> fix: keep re-auth issue

- CHANGELOG.md
- client/src/components/ContentNavigator/ContentModel.ts
- client/test/components/ContentNavigator/ContentDataProvider.test.ts
**Summary**
Fix #225 
Add sortBy parameter when querying the members of a folder.
**Testing**
As described in #225.
Run unit tests
> fix: correct content order (#225)

- client/src/components/AuthProvider.ts
**Summary**
Fix #235
AuthenticationProvider should fire change event for VS Code Accounts menu to update.
**Testing**
Test case in #235
> fix: authentication provider should fire proper event

- CHANGELOG.md
- client/src/commands/run.ts
- client/src/node/extension.ts
- package.json
- package.nls.json
- server/src/sas/LanguageServiceProvider.ts
- server/src/server.ts
**Summary**
Support #222
**Testing**
Select `Run Region` from context menu, see correct SAS code block where current cursor/selection belongs run.
> feat: run region

- server/src/sas/SyntaxDataProvider.ts
**Summary**
Fix #259
**Testing**
Test case in #259
> fix: let builtin suggestion popup

- client/src/components/DragAndDropController.ts
- client/src/components/LibraryNavigator/LibraryDataProvider.ts
- client/src/components/LibraryNavigator/LibraryModel.ts
**Summary**
Fix #250, #252 and #265
Library model has to reset session id on profile change
Also cleaned up some unused fields in LibraryModel
**Testing**
Test case in #250
> fix: library model has to reset session id on profile change

- client/src/connection/rest/index.ts
**Summary**
Fix #295
**Testing**
Test case in #295
> fix: error when run code

- client/src/components/ContentNavigator/ContentDataProvider.ts
- client/src/components/ContentNavigator/ContentModel.ts
- client/src/components/ContentNavigator/const.ts
- client/src/components/ContentNavigator/utils.ts
- client/test/components/ContentNavigator/ContentDataProvider.test.ts
- icons/dark/deleteDark.svg
- icons/dark/favoritesFolderDark.svg
- icons/dark/folderDark.svg
- icons/dark/sasFoldersDark.svg
- icons/light/deleteLight.svg
- icons/light/favoritesFolderLight.svg
- icons/light/folderLight.svg
- icons/light/sasFoldersLight.svg
**Summary**
fix #214 
change icons for My Favorites, Recycle Bin, SAS Content and normal folder
> change folders icon

- CHANGELOG.md
- client/src/components/LibraryNavigator/LibraryModel.ts
**Summary**
Fix #300
Viya 3.5 appears requiring accept header at more places.
**Testing**
Tested library view on both Viya 3.5 and Viya 4
> fix: several library requests need accept header

- CHANGELOG.md
**Summary**
This updates the changelog for sas content
**Testing**
👀
> chore: update changelog for sas content changes

- package.json
**Summary**
Fix #371
**Testing**
Test case in #371
> fix config name (#371)

- .gitignore
- .vscodeignore
- client/package-lock.json
- client/package.json
- client/src/commands/profile.ts
- client/src/commands/run.ts
- client/src/components/ContentNavigator/ContentDataProvider.ts
- client/src/components/ContentNavigator/const.ts
- client/src/components/ContentNavigator/index.ts
- client/src/components/LibraryNavigator/LibraryModel.ts
- client/src/components/LibraryNavigator/const.ts
- client/src/components/LogChannel.ts
- client/src/components/notebook/Controller.ts
- client/src/components/profile.ts
- client/src/connection/index.ts
- client/src/connection/rest/auth.ts
- client/src/connection/rest/context.ts
- client/src/connection/rest/index.ts
- client/src/connection/rest/job.ts
- client/src/connection/rest/server.ts
- client/src/connection/rest/session.ts
- client/src/connection/ssh/index.ts
- client/src/node/extension.ts
- client/test/components/LibraryNavigator/LibraryDataProvider.test.ts
- package-lock.json
- package.json
- package.nls.json
**Summary**
Support #189 with [vscode-l10n](https://github.com/microsoft/vscode-l10n).
Added a `pseudoLocalize` script.
Note that it only applies to `client` directory. `server` is already localized with SAS tooling.
**Testing**
1. Checkout branch code
2. `npm install`, `npm run pseudoLocalize`, `vsce package`
3. Install the vsix
4. Install [Pseudo Language Language Pack](https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-qps-ploc) extension
5. Run `Configure Display Language` command and switch to the Pseudo Language. (It requires restart)
6. See UI text provided by the extension are pseudo translated.
> feat: l10n infrastructure

- client/src/connection/com/index.ts
- client/src/connection/session.ts
- client/src/connection/ssh/index.ts
**Summary**
As my https://github.com/sassoftware/vscode-sas-extension/issues/393#issuecomment-1633781315
Let me go ahead remove them so that we're in a good state to release.
Anytime it can be implemented and will just work fine.
**Testing**
See no cancel button while running against COM and SSH because we don't support it yet.
> fix: should not show cancel button if not supported

- client/src/components/ContentNavigator/ContentDataProvider.ts
**Summary**
Fix #418
**Testing**
Test case in #418
> fix: close notebook before delete

- connect-and-run.md
Update connect-and-run.md for the new added SAS Options and AutoExec settings in profiles
> doc: update README

- server/src/sas/CompletionProvider.ts
**Summary**
Input lowercase or uppercase keyword per user input
**Testing**
manual testing
> feat: honor Caps Lock status when autocompletion.

- client/src/connection/ssh/index.ts
**Summary**
Fix #470
Now that the onLog callback is set before setup. Thus the session startup log will show along the way. There's no need to show previous log when run.
**Testing**
Test case in #470
> fix: do not show previous log for ssh

- client/src/connection/com/index.ts
- client/test/connection/com/index.test.ts
**Summary**
Fix #472
The setup resolve in COM should not rely on `_onLogFn`
**Testing**
Test case in #472
> fix: notebook run complete on com

- client/src/components/ContentNavigator/ContentDataProvider.ts
- client/src/components/ContentNavigator/index.ts
**Summary**
Fix #445
- File should be opened by "vscode.open" command instead of `window.showTextDocument` for non-text document.
- The dirtyFiles check is not needed. The DataProvider will `closeFileIfOpen` - native way to prompt user if they want to save.
- We should only re-open the file if it was opened before rename.
- The type for `closeFileIfOpen` is not exact, it should be `true | Thenable<boolean>`. We don't need to write it, TS will infer correctly.
**Testing**
Test case in #445
> fix: correctly re-open files for content rename

- server/src/sas/CodeZoneManager.ts
**Summary**
Fix #497
**Testing**
Test case in #497
> fix: call routine autocomplete

- CHANGELOG.md
- package.json
**Summary**
Update relevant release doc for 1.4.1
**Testing**
Manual Inspection
> chore: release doc

- client/src/components/profile.ts
**Summary**
Fix #514
**Testing**
Test case in #514
> fix: display target for local profile

- .github/workflows/package.yml
**Summary**
Store the built vsix file as artifact so that anyone can download and directly play with PR or latest main branch without build effort.
**Testing**
See artifact for this build https://github.com/sassoftware/vscode-sas-extension/actions/runs/6571171460
> chore: store built vsix

- client/src/components/utils/sasCode.ts
**Summary**
Fix #471
Wrap ODS statement similar to SAS Studio
**Testing**
Test case in #471
> fix: ODS display image inline

- package.json
**Summary**
Fix #607
**Testing**
Test case in #607
> fix: sasnb extension name

- client/test/extension.test.ts
- client/testFixture/SampleCode2.sas
- server/messagebundle.properties
- server/messagebundle_zh_CN.properties
- server/messagebundle_zh_TW.properties
- server/src/sas/CompletionProvider.ts
- server/src/sas/SyntaxDataProvider.ts
- server/src/server.ts
**Summary**
Add support for function context prompt after entering a function name. See https://github.com/sassoftware/vscode-sas-extension/issues/66 for more details.
**Testing**
Tested entering a normal sas function.
Tested entering a nested sas function within another sas function.
Tested entering a sas macro function.
> feat: support function context prompt

- tools/locale.mjs
**Summary**
Self-explanatory
**Testing**
- Tested running script with relative and absolute file paths
> chore: update locale tool to support absolute paths

- connect-and-run.md
**Summary**
Doc autoexec and SAS options
**Testing**
Visual inspection
> doc: autoexec and sas options

- client/test/languageServer/formatter.test.ts
- client/testFixture/formatter/expected.sas
- client/testFixture/formatter/unformatted.sas
- package.json
- server/src/sas/LanguageServiceProvider.ts
- server/src/sas/Lexer.ts
- server/src/sas/LexerEx.ts
- server/src/sas/formatter/index.ts
- server/src/sas/formatter/parser.ts
- server/src/sas/formatter/printer.ts
- server/src/sas/utils.ts
- server/src/server.ts
**Summary**
Resolve #28
**Testing**
1. Open a `.sas` file
2. Open context menu and select `Format Document`
3. See formatted SAS code
> feat: support formatting SAS code

- client/src/node/extension.ts
**Summary**
Fix #745
It has to close current session whenever profile changed
**Testing**
Test case in #745
> fix: close session when profile changed

- CHANGELOG.md
**Summary**
Moves the settings fix to a new unreleased section
**Testing**
Visual Inspection
> doc: move options fix to 1.7.0

- server/src/sas/LexerEx.ts
- server/src/server.ts
**Summary**
Fix #772
**Testing**
Test case in #772
> fix: end inner block properly inside macro

- CONTRIBUTING.md
**Summary**
This updates our contributor list and sorts things alphabetically
**Testing**
👀
> update contributors for es locale

- client/src/components/utils/sasCode.ts
**Summary**
This prevents viya connections from generating uuid based files
**Testing**
> fix: prevent viya from generating guid based html files

- server/src/sas/formatter/parser.ts
**Summary**
Fix #848
**Testing**
Test case in #848
> fix: formatting issue when lua submit block is empty

- client/src/connection/itc/index.ts
- client/src/connection/itc/script.ts
- client/src/connection/itc/types.ts
**Summary**
Support #506
**Testing**
See Error/Warning/Note colors for SAS log with Local 94 and IOM connections.
> feat: SAS log colors for Local 94 and IOM

- server/src/sas/CodeZoneManager.ts
**Summary**
Fix #954, #900
**Testing**
Test case in #954, #900
> fix: syntax help issue in special case

- client/src/components/logViewer/ProblemProcessor.ts
**Summary**
There is logic issue to detect if two code lines are same. 
**Testing**
See #1019 description
> fix: update code to detect if two code lines are same (fixes #1019)

- client/src/commands/run.ts
- client/src/components/tasks/SasTasks.ts
**Summary**
Log will be shown in output panel
Fix #1058 
**Testing**
Run task
see log is shown in output panel
> fix: output log in running tasks

- server/src/sas/CodeZoneManager.ts
- server/src/sas/FormatOnTypeProvider.ts
**Summary**
Resolve https://github.com/sassoftware/vscode-sas-extension/issues/652, revise the logic of the _getIndentIncrementOfNextLine function and _getSemicolonTriggeredIndentEdit function.
**Testing**
Type "%macro test (test);" and "enter", Indentation works properly.
> fix: revise logic of _getIndentIncrementOfNextLine function and _getSemicolonTriggeredIndentEdit function

- client/src/components/notebook/Controller.ts
**Summary**
Fix #1080
**Testing**
Test case in #1080
> fix: clear cell output before cell executing

- .github/dependabot.yml
- client/package-lock.json
- client/package.json
- package-lock.json
- package.json
- server/src/sas/utils.ts
- website/package-lock.json
- website/package.json
Combine dependabot PRs to resolve build issues
> chore(deps): bump dependencies versions

- .github/dependabot.yml
- website/package-lock.json
- website/package.json
By default dependabot updates dependencies ony by one. Some dependencies must be upgraded together otherwise the version mismatch may cause issues.
> fix: build issue

- website/docs/Configurations/Profiles/sas9ssh.md
- website/docs/faq.md
**Summary**
Update doc per request from @snlwih
Content reviewed by @jennifert-sas
**Testing**
See updated doc
> doc: update doc for console log

- client/src/connection/itc/index.ts
- client/src/connection/itc/script.ts
- client/test/connection/itc/index.test.ts
**Summary**
Fix #1119
Get working directory via IOM API instead of SAS log
**Testing**
Tested with COM and IOM connections and the result can be fetched correctly.
> fix: get working directory via IOM API

- website/docs/faq.md
**Summary**
Updated FAQ. Reviewed by @jennifert-sas
**Testing**
See updated doc
> doc: update faq

- client/src/components/tasks/SasTasks.ts
**Summary**
Fix #1177
**Testing**
Test case in #1177
> fix: run selected text with run task

- client/src/components/logViewer/logParser.ts
**Summary**
Fix #1201
**Testing**
Test case in #1201
> fix: exception with empty user code

- server/src/sas/CodeZoneManager.ts
- server/src/sas/Lexer.ts
**Summary**
Fix #1202
**Testing**
Test case in #1202
> fix: formatting fedsql code lost issue

- client/src/commands/run.ts
- client/src/components/utils/SASCodeDocument.ts
**Summary**
Fix #1223
**Testing**
Test case in #1223
> fix: display filename rather than Uri

- client/testFixture/formatter/expected.sas
- client/testFixture/formatter/unformatted.sas
- server/src/sas/formatter/parser.ts
**Summary**
Fix #1226
**Testing**
Test case in #1226
> fix: formatting should allow statements between proc python and submit

- server/src/sas/CompletionProvider.ts
**Summary**
Fix #1267
**Testing**
Test case in #1267
> fix: don't show help when hover on white space

- client/src/webview/DataViewer.tsx
- client/tsconfig.json
- eslint.config.mjs
**Summary**
https://legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html
**Testing**
Verify that data viewer works well as before
> chore: use new jsx transform

- server/src/sas/CompletionProvider.ts
**Summary**
Fix #1282
**Testing**
Test case in #1282
> fix: display global option help in data step

- server/src/sas/CompletionProvider.ts
**Summary**
Fix #1306
**Testing**
Test case in #1306
> fix: display context in hover help for data step statement option

- client/src/components/logViewer/DiagnosticCodeActionProvider.ts
- client/src/components/logViewer/sasDiagnostics.ts
**Summary**
Fix #1302
Currently the Pyright doesn't provide any quick fixes.
**Testing**
Test case in #1302
> fix: sas log code action should not impact others

- server/src/python/sas/sas2py.pyi
- server/src/python/utils.ts
- tools/build.mjs
**Summary**
Fix #1301
Add sas2py as built-in stub
**Testing**
Test case in #1301
> fix: support SAS module help in PROC PYTHON

- website/package-lock.json
- website/package.json
Reverts sassoftware/vscode-sas-extension#1315
> Revert "chore(deps): bump the react group in /website with 2 updates"

- client/src/webview/DataViewer.tsx
- client/src/webview/useDataViewer.ts
**Summary**
Fix #1334
Resolve breaking changes introduced by AG Grid v33
**Testing**
See data table correctly
> fix: resolve breaking changes by AG Grid 33

- client/src/components/logViewer/index.ts
- server/src/python/browser/typeshed-loader/index.js
**Summary**
Fix #1325
The line returned by server appears to contain `\n` in this case
**Testing**
Test case in #1325
> fix: log color issue

- server/src/sas/FormatOnTypeProvider.ts
- server/src/sas/LanguageServiceProvider.ts
- server/src/sas/SyntaxProvider.ts
**Summary**
Fix #1376
**Testing**
Test case in #1376
> fix: proc python auto-indent

- website/docs/Features/sasNotebook.md
**Summary**
Resolves #1426
Content reviewed by @jennifert-sas and @snlwih 
**Testing**
See updated doc
> doc: add note for SQL cell

- .github/workflows/package.yml
- .github/workflows/pr.yml
**Summary**
See https://github.com/microsoft/vscode-vsce/issues/1147
**Testing**
See build pass
> build: allow secret for false positive

- CHANGELOG.md
- client/src/commands/authorize.ts
- client/src/commands/run.ts
- client/src/components/ContentNavigator/ContentAdapterFactory.ts
- client/src/components/ContentNavigator/ContentDataProvider.ts
- client/src/components/ContentNavigator/ContentModel.ts
- client/src/components/ContentNavigator/types.ts
- client/src/components/ContentNavigator/utils.ts
- client/src/connection/itc/CodeRunner.ts
- client/src/connection/itc/ITCSASServerAdapter.ts
- client/src/connection/itc/ItcLibraryAdapter.ts
- client/src/connection/itc/index.ts
- client/src/connection/itc/script.ts
- client/src/connection/itc/types.ts
- client/src/connection/itc/util.ts
- client/src/connection/rest/RestSASServerAdapter.ts
- client/src/connection/util.ts
- client/src/node/extension.ts
- client/test/connection/itc/index.test.ts
- package.json
- website/docs/Features/accessServer.md
- website/docs/matrix.md
**Summary**
This adds sas file system support for sas9 file system for IOM/COM connection types. Additionally, it includes a small refactor to the way interop libraries are loaded. Loading them at SASRunner construction occurs too late, and doesn't provide the type-checking necessary for file service.
**Testing**
> feat: implement sas file system for IOM/COM connections

- .github/workflows/package.yml
- .github/workflows/pr.yml
Reverts sassoftware/vscode-sas-extension#1485
vsce v3.4.1 fixed the issue.
> Revert "build: allow secret for false positive"

- client/src/components/ContentNavigator/index.ts
- client/src/connection/rest/util.ts
**Summary**
Fix https://github.com/sassoftware/vscode-sas-extension/issues/1532
**Testing**
the xxx?.sas can be open now;
the icon in the tree view is a correct sas icon;
it can create the xxx#.sas file from extension.
> fix:deal with the question mark

- client/src/components/ContentNavigator/const.ts
- client/src/components/ContentNavigator/index.ts
- package.json
**Summary**
Fix https://github.com/sassoftware/vscode-sas-extension/issues/789
**Testing**
Press key to delete file or dir
> fix:delete a file or file folder through keyboard

- server/src/sas/CodeZoneManager.ts
- server/src/sas/LexerEx.ts
**Summary**
Fix #1555
**Testing**
Test case in #1555
> fix: autocomplete for sub-options

- pull_request_template.md
**Summary**
This adds a new item to the pull request template, reminding users to update changelogs and
update documentation for changes
> chore: update pull_request_template.md
